---
- name: Ensure summon lib folder exists
  file:
    path: "{{ summon_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Download summon archive
  get_url:
    url: "{{ summon_download_url }}"
    dest: /tmp/summon.tar.gz
    mode: 0644
    checksum: "{{ summon_checksum }}"
  changed_when: false

- name: Extract summon archive
  unarchive:
    src: /tmp/summon.tar.gz
    dest: "{{ summon_path }}"
    creates: "{{ summon_path }}/summon"
    owner: root
    group: root
    remote_src: yes
  become: true

- name: Remove summon archive
  file:
    path: /tmp/summon.tar.gz
    state: absent
  changed_when: false

- name: Create summon symlink
  file:
    src: "{{ summon_path }}/summon"
    dest: "{{ summon_bin }}"
    owner: root
    group: root
    state: link
    force: true
  become: true
