---
- name: Ensure summon lib folder exists
  ansible.builtin.file:
    path: "{{ summon_path }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
  become: true

- name: Download summon archive
  ansible.builtin.get_url:
    url: "{{ summon_download_url }}"
    dest: /tmp/summon.tar.gz
    mode: 'u=rw,go=r'
    checksum: "{{ summon_checksum }}"
  changed_when: false

- name: Extract summon archive
  ansible.builtin.unarchive:
    src: /tmp/summon.tar.gz
    dest: "{{ summon_path }}"
    creates: "{{ summon_path }}/summon"
    owner: root
    group: root
    remote_src: true
  become: true

- name: Remove summon archive
  ansible.builtin.file:
    path: /tmp/summon.tar.gz
    state: absent
  changed_when: false

- name: Create summon symlink
  ansible.builtin.file:
    src: "{{ summon_path }}/summon"
    dest: "{{ summon_bin }}"
    owner: root
    group: root
    state: link
    force: true
  become: true
