---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check summon version
    ansible.builtin.command: summon --version
    register: output
  - name: Assert that summon is installed
    ansible.builtin.assert:
      that:
      - "'summon version' in output.stdout"
